commerce/auctions/urls.py
from django.urls import path, re_path

from . import views

app_name = 'auctions'
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("create_listing/", views.create_listing, name="create_listing"),
    path("listing/<int:listing_id>/", views.listing, name="listing"),
    re_path(r"^listing/(?P<listing_id>\d+)/(?:(.+)/$)", views.listing, name="listing"),
    path("watchlist/", views.watchlist, name="watchlist"),
    path("watchlist/<int:listing_id>/", views.watchlist, name="watchlist"),
    path("category/", views.category, kwargs={'category_name': None}, name="category"),
    path("category/<str:category_name>/", views.category, name="category"),
    

]

# path("listing/<str:title>/", views.listing, name="listing"),
# re_path(r"^watchlist/$", views.watchlist, name="watchlist"),

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime
from django.forms import ModelForm, Textarea, DateTimeInput, TextInput, NumberInput
from django import forms
from django.utils.translation import gettext as _


class User(AbstractUser):
    pass


class Listing(models.Model):
    
    CategoryType = models.TextChoices('CategoryType', 
        ['ELECTRONICS',
        'FASHION',
        'HOME_&_OFFICE',
        'TOYS',
        'SPORTING_GOODS',
        'BABY_PRODUCTS',
        'OTHER']
    ) 
    
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    title = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=256)
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=20, choices=CategoryType.choices, default='ELECTRONICS')
    image_url = models.URLField(blank="True")
    active = models.BooleanField(default="True")
    
    def __str__(self):
        return f'{self.title}'
    

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f'${self.amount} - {self.listing.title}'

class Comment(models.Model): 
    commentor = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=200)
    time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.content[:25]}...'

class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_watchlist")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="watchlist")


class NewListingForm(ModelForm):
    class Meta:
        exclude = ['created_by', 'active']
        model = Listing
        widgets = {
              'description': Textarea(attrs={'cols': 70, 'rows': 7}),
              'starting_bid': NumberInput(attrs={'min': 0})
          }


class BiddingForm(ModelForm):
    class Meta:
        
        
        fields = ['amount']
        # widgets = {
        #     'amount': NumberInput(attrs={'min': Bid.objects.filter()}),
        # }
        help_texts = {
            'amount': _('Enter an amount to bid.'),
        }

        error_messages = {
            'amount': {
                'min': _('Amount should be larger than: ')
            }
        }


class BidForm(forms.Form):
    bidder_id = forms.IntegerField(min_value=0)
    amount = forms.DecimalField(max_digits=10, decimal_places=2)



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['commentor', 'listing']
        widgets = {
            'content': Textarea
        }
"""    
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.fields['name'].widget.attrs.update({'class': 'special'})
self.fields['comment'].widget.attrs.update(size='40')

"""

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.db.models import F, Exists, OuterRef

from decimal import Decimal

from .models import *


# Templates
INDEX_TEMPLATE = "auctions/index.html"
LISTING_TEMPLATE = "auctions/listing.html"
REGISTER_TEMPLATE = "auctions/register.html"

def index(request):
    context = {
        'listings': Listing.objects.order_by('-active'),
    }
    if request.user.is_authenticated:
        listings = Listing.objects.annotate(
            is_on_watchlist=Exists(Watchlist.objects.filter(listing=OuterRef('pk'), user=request.user))
            ).order_by('-active')
        context['listings'] = listings
    return render(request, INDEX_TEMPLATE, context=context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            print(request.user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, REGISTER_TEMPLATE, {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, REGISTER_TEMPLATE, {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, REGISTER_TEMPLATE)


@login_required
def create_listing(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            Listing.objects.create(
                created_by = request.user,
                title = form.cleaned_data['title'],
                description = form.cleaned_data['description'],
                starting_bid = form.cleaned_data['starting_bid'],
                category = form.cleaned_data['category'],
                image_url = form.cleaned_data['image_url']
                )

            return HttpResponseRedirect(reverse('auctions:index'))
    else:
        form = NewListingForm()

    return render(request, "auctions/create_listing.html", {
        'new_listing': form,
    })


def listing(request, listing_id): 
    listing = Listing.objects.get(id=listing_id)

    comments = listing.comments.order_by('-time').annotate(username=F('commentor__username'))
    
    # Get highest bid
    highest_bid = listing.bids.order_by('-amount')
    if highest_bid:
        highest_bidder = highest_bid[0].bidder.username
        highest_bid = highest_bid[0].amount
    else:
        highest_bid = listing.starting_bid
        highest_bidder = None

    context = { 
        'listing': listing,
        'bid_form': BiddingForm,
        'comment_form': CommentForm,        
        'comments': comments,
        'highest_bidder': highest_bidder,
        'highest_bid': highest_bid,
    }

    user = request.user
    if user.is_authenticated:
        # Check if listing is on watchlist
        listing_watchlist_count = listing.watchlist.filter(user=user).count()
        context['is_on_watchlist'] = True if listing_watchlist_count > 0 else False
    if request.method == "POST":

        # Check if listing is on watchlist
        
        action = request.POST['action']

        # A comment is being submitted
        if action == "comment":
            listing.comments.create(
                commentor=user,
                content=request.POST['content']
            )    
            return HttpResponseRedirect(reverse('auctions:listing', args=[listing_id, listing.title]))

        # Close the bidding
        elif action == "close":   
            # Close the bid, and get the highest bidder
            listing.active = "False"
            listing.save()  
            return HttpResponseRedirect(reverse('auctions:listing', args=[listing_id, listing.title]))

        else:  
            # A bid is being placed
            # Receive the form data about the bid
            form = BidForm(request.POST)
            amount = request.POST['amount']    
            if amount: 
                submitted_bid = Decimal(amount) 
                
                if highest_bid:
                    
                    if submitted_bid > highest_bid:
                        # listing already has bids on it
                        listing.bids.create(
                            bidder_id=user.id, 
                            amount=submitted_bid
                        )
                        context['highest_bid'] = submitted_bid
                        context['form_validity'] = "is-valid"
                        return HttpResponseRedirect(reverse('auctions:listing', args=[listing_id, listing.title]))
                    else:
                        # submitted_bid is less than current highest bid
                        context['form_validity'] = "is-invalid"
                        return HttpResponseRedirect(reverse('auctions:listing', args=[listing_id, listing.title]))
                        
                else:
                    # Listing has no bids yet
                    listing.bids.create(
                        bidder_id=user.id, 
                        amount=submitted_bid
                    )
                    context['form-validity'] = "is-valid"
                    context['highest_bid'] = submitted_bid
                
                    # context['listing'] = Bid.objects.filter(listing_id=listing_id).order_by('-amount')[0]
                    return HttpResponseRedirect(reverse('auctions:listing', args=[listing_id, listing.title]))

            else:   
                # form is not valid
                # Return form with submitted values
                context['bid_form'] = form
                return render(request, LISTING_TEMPLATE, context=context)
 
    # Request is GET
    else:   
        return render(request, LISTING_TEMPLATE,
        context=context)


@login_required
def watchlist(request, listing_id=None):
    
    user = request.user
    watchlist = Watchlist.objects.filter(user=user)

    watchlist = Listing.objects.filter(
        id__in=watchlist.values('listing_id')).annotate(
            is_on_watchlist=Exists(watchlist)
        )    
    if request.method == "POST":
        action = request.POST["action"]
        
        if action == "add":
            # Add listing to watchlist
            user.user_watchlist.create(listing_id=listing_id)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:   
            # Remove listing from watchlist
            Watchlist.objects.filter(user=user, listing_id=listing_id).delete()
            return HttpResponseRedirect(reverse("auctions:index"))
   
    else:   # Request is get
        return render(request, "auctions/watchlist.html", {
            'watchlist': watchlist,
        })
    

def category(request, category_name):
    CATEGORIES = Listing.category.field.choices
    categories = [item[1] for item in CATEGORIES]
    categories.insert(0, 'All')

    context = {
            'listings_by_category': Listing.objects.filter(category__iexact=category_name).order_by('-active'), 
            'categories': categories,
            }
    
    if category_name == 'All':
        context['listings_by_category'] = Listing.objects.order_by('-active')     

    return render(request, "auctions/category.html",
        context=context
    )


class BidForm(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    listing_id = forms.IntegerField(max_value=150, min_value=0)
    

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block heading %}
    <h2>Categories</h2>
{% endblock %}

{% block body %}
    <div class="rounded mb-5">
        <div class="mb-3">Select a category below:</div>
        <ul class="list-unstyled list-inline text-center">
        {% for category in categories %}                              
            <li class="list-inline-item"><a href="{% url 'auctions:category' category %}" class="btn btn-sm btn-outline-primary">{{ category }}</a></li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="">
        {% include 'auctions/for_each_listing.html' with empty_msg="No listings under this category" list=listings_by_category %}
    </div>    

{% endblock %}


commerce/auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}
{% load myfilters %}


{% block body %}

    <div class="form">
        <form action="{% url 'auctions:create_listing' %}" method="POST">
            {% csrf_token %}
            {% for field in new_listing %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field|addclass:'form-control' }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Sumbit</button>
        </form>
    </div>

{% endblock %}

commerce/auctions/templates/auctions/for_each_listing.html
<div class="all-listings row">
    {% for item in list %}
        <div class="col-xl-3 col-sm-4 mb-3">
            <div class="card active-{{ item.active }} p-3" >
                <a href="{% url 'auctions:listing' item.id item.title %}">    
                    <img 
                        src="{{ item.image_url }}"
                        alt="{{ item.title }}" 
                        class="card-img-top"
                    />
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ item.title }}</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item item-price">Price: ${{ item.starting_bid }}</li>
                        <li class="list-group-item created">Created {{ item.created_at }}</li>
                    </ul>   
                </a>

                <!-- Watchlist Section -->
                {% if user.is_authenticated and item.active %}
                    <form action="{% url 'auctions:watchlist' item.id %}" method="POST" class="text-center">
                        {% csrf_token %}                    
                        {% if item.is_on_watchlist %}
                            <input name="action" value="remove" type="hidden">
                            <button type="submit" class="btn btn-primary">Remove from Watchlist</button>
                        {% else %}
                            <input name="action" value="add" type="hidden">
                            <button type="submit" class="btn btn-primary">Add to Watchlist</button>
                        {% endif %}
                    </form>
                {% endif %}  
            </div>
        </div>
    {% empty %}
        <div class="text-info text-center w-100 mt-5 fs-4">{{ empty_msg }}</div>
    {% endfor %}
</div>

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block heading %}
    <h2>Active Listings</h2>
{% endblock %}

    
{% block body %}
    {% include 'auctions/for_each_listing.html' with list=listings empty_msg='No listings have been posted yet' %}
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}
{% load myfilters %}
<!DOCTYPE html>
<html lang="en">
  <head>
		<title>{% block title %}Auctions{% endblock %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="{% static 'auctions/styles.css' %}?{% now 'U' %}" rel="stylesheet">
  </head>
  <body>
	  <div class="container-fluid">
		<h1>Auctions</h1>
		<div>
			{% if user.is_authenticated %}
					Signed in as <strong>{{ user.username }}</strong>.
			{% else %}
					Not signed in.
			{% endif %}
		</div>
		<ul class="nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'auctions:category' 'All' %}">Categories</a>
			</li>

				{% if user.is_authenticated %}

					<li class="nav-item">
						{# {% with listing_id=2 %} #}
							<a class="nav-link" href="{% url 'auctions:watchlist' %}">
								Watchlist <span class="badge badge-light">{{ user.user_watchlist.all.count }}</span>
							</a>
						{# {% endwith %} #}
					</li>  
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listing</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
					</li>

				{% else %}

			<li class="nav-item">
				<a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
			</li>
			{% endif %}
		</ul>
		<hr>
		{% block body %}
		{% endblock %}
	</div>
  </body>
</html>

commerce/auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}
{% load myfilters %}

{% block body %}
	<div class="main">
		<div class="card mb-3 p-3">
			<div class="row g-0">
			  <div class="col-md-4">
				<img src="{{ listing.image_url }}" class="listing-pg-img" alt="{{ listing.title }}">
				<!-- Watchlist -->
				{% if user.is_authenticated and listing.active %}
					<form action="{% url 'auctions:watchlist' listing.id %}" method="POST" class="text-center my-3">
						{% csrf_token %}
						
						<!-- Checking if item is on watchlist -->
						{% if is_on_watchlist %}
							<div>
								<!--  remove from watchlist -->
								<input type="hidden" name="action" value="remove">
								<button class="btn btn-primary" type="submit">Remove from watchlist</button>
							</div>
						{% else %} 
							<div>
								<!-- Add to watchlist -->
								<input type="hidden" name="action" value="add">
								<button class="btn btn-primary" type="submit">Add to watchlist</button>
							</div>
						{% endif %}
					</form>
				{% endif %}
			  </div>
			  <div class="col-md-8">
				<div class="card-body">
				  <h5 class="card-title">{{ listing.title }}</h5>
				  <p class="card-text">{{ listing.description }}.</p>
				</div>
				<div class="listing-details">
					<ul class="list-group list-group-flush">
						<li class="list-group-item item-price">Listed by: {{ listing.created_by }}</li>
                        <li class="list-group-item created">Category: {{ listing.category }}</li>
					</ul>
				</div>
				<div class="price-info">
					{% if listing.active %}
						Starting bid: <strong>${{ listing.starting_bid }}</strong>
						{% if highest_bid > listing.starting_bid %}
							<p class="fs-4 text-info mt-2">Current bid: <strong>${{ highest_bid }}</strong> by {{ highest_bidder }}</p>
						{% else %}
							<p class="fs-4 text-info mt-3">No bids yet</p>
						{% endif %}
					{% else %}
						<div class="listing-status bg-success text-center text-white position-absolute border border-success p-3">
							<div>Bidding is closed.</div>
							{% if highest_bidder|stringformat:"s" == request.user|stringformat:"s" %}
								<div>You won this bidding.</div>
							{% else %}
								<div>{{ highest_bidder }} won this bidding</div>
							{% endif %}
						</div>
					{% endif %}
				</div>
				<!-- Bidding Section -->
				<div class="bidding-sec">
					{% if user.is_authenticated and listing.active %}
						<div class="listing-biz">
							<!-- Checking if current user created this listing -->
							<!-- If true, then allow user to close bid -->
							{% if request.user|stringformat:"s" == listing.created_by|stringformat:"s" %} 
								<form action="{% url 'auctions:listing' listing.id listing.title %}" method="POST">
									{% csrf_token %}
									<button type="submit" name="action" value="close" class="btn btn-primary">Close bidding</button>
								</form>
							{% else %}  
							<!-- Bid placement form -->
								<form action="{% url 'auctions:listing' listing.id listing.title %}" method="POST" class="row row-cols-lg-auto ml-0 g-3 align-items-center">
									{% csrf_token %} 
								<!-- Alert messages -->
									{% if form_validity == "is-invalid" %}
										<div class="alert alert-danger" role="alert">
											Bid should be larger than the current highest bid
										</div>
									{% elif form_validity == "is-valid" %}
										<div class="alert alert-success" role="alert">
											Bid successfully placed
										</div>
									{% else %}
									{% endif %}
									
									<div class="form row">
										<div class="input-group mb-3">
											<span class="input-group-text sm">$</span>
											<input type="number" name="amount" min="{{ highest_bid|add:1 }}" class="form-control {{ form_validity }}" aria-label="Amount (to the nearest dollar)" required>
											<input type="hidden" name="action" value="bid">
											<span class="input-group-text">.00</span>
											<div class="invalid-feedback">Amount should be larger than ${{ highest_bid|add:1 }}</div>
											<button type="submit" class="btn ml-3 btn-primary">Submit</button>   
										</div>
									</div>
								
								</form>
							{% endif %}
							
						</div>
					{% endif %}
				</div>
			  </div> <!---End col-md-8-->
			</div>
		</div>

		<div class="comment-section mt-5 w-50">
			{% if user.is_authenticated %}
				<div class="comment-form">
					<form action="{% url 'auctions:listing' listing.id listing.title %}" method="POST">
						{% csrf_token %}
						<textarea class="form-control mb-2" name="content" placeholder="Enter your comments here..."></textarea>
						<input type="hidden" name="listing_id" value="{{ listing.id }}">
						<button class="btn btn-primary" type="submit" name="action" value="comment">Submit</button>
					</form>
				</div>
			{% else %}
				<div class="mb-4"><a href="{% url 'auctions:login' %}">Login to comment</a></div>
			{% endif %}
				<div class="comments-heading"> 
					<h6>ALL COMMENTS</h6>
				</div>
				<div class="comments-display row">
					<ol class="comment-list">    
						{% for comment in comments %}
							<li class="comment">    
								<div class="comment-meta">
									
									{% if user|stringformat:"s" == comment.username|stringformat:"s" %}
										<div class="comment-author">You</div>
									{% else %}
										<div class="comment-author">{{ comment.username }}</div>
									{% endif %}
									<div class="comment-time">{{ comment.time.ctime }}</div>
								</div>
								<p class="comment-content">{{ comment.content }}</p> 
							</li>
						{% empty %}
							<p class="text-center mt-3">Be the first to comment on the listing.</p>
						{% endfor %}
					</ol>
				</div>
		</div>
	</div>

{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div class="text-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div class="text-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% block heading %}
    <h2>Watchlist</h2>
{% endblock %}

{% block body %}
        {% include 'auctions/for_each_listing.html' with list=watchlist empty_msg="You haven't added any listing to the watchlist" %}
{% endblock %} 

